# Generated by Django 5.1.7 on 2025-03-30 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagasonline_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidato',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidato',
            name='photo',
            field=models.FileField(default='candidato_photo', upload_to='img'),
        ),
    ]
