# Generated by Django 5.1.7 on 2025-04-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagasonline_app', '0002_candidato_add_date_candidato_idade_candidato_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='photo',
        ),
        migrations.AddField(
            model_name='candidato',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='email',
            field=models.EmailField(default='defaul@email.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='endereco',
            field=models.CharField(default='Endereço não informado', max_length=150),
        ),
        migrations.AddField(
            model_name='candidato',
            name='genero',
            field=models.CharField(default='Genero não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='candidato',
            name='telefone',
            field=models.CharField(default='Telefone não informado', max_length=30),
        ),
        migrations.AddField(
            model_name='candidato',
            name='vaga',
            field=models.CharField(default='Não informado', max_length=100),
        ),
    ]
