# Generated by Django 5.1.7 on 2025-04-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagasonline_app', '0003_remove_candidato_photo_candidato_curriculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='./media/curriculos'),
        ),
    ]
